blueprint:
  name: Controller - Philips 929003017102 Hue wall switch module
  description: "# Controller - Philips 929003017102 Hue wall switch module"
  source_url: https://github.com/certifield/ha-blueprints/blob/main/Philips_929003017102.yaml
  domain: automation
  input:
    integration:
      name: (Required) Integration
      description: Integration used for connecting the remote with Home Assistant.
        Select one of the available values.
      selector:
        select:
          options:
          - ZHA
          - Zigbee2MQTT
          multiple: false
          custom_value: false
    controller_device:
      name: (ZHA) Controller Device
      description: The controller device to use for the automation. Choose a value
        only if the remote is integrated with ZHA.
      default: ''
      selector:
        device: {}
    controller_entity:
      name: (Zigbee2MQTT) Controller Entity
      description: The action sensor of the controller to use for the automation.
        Choose a value only if the remote is integrated with Zigbee2MQTT.
      default: ''
      selector:
        entity:
          domain: sensor
          multiple: false
    helper_last_controller_event:
      name: (Required) Helper - Last Controller Event
      description: Input Text used to store the last event fired by the controller.
        You will need to manually create a text input entity for this, please read
        the blueprint Additional Notes for more info.
      default: ''
      selector:
        entity:
          domain: input_text
          multiple: false